### ISSUE TITLE
when i use the mod in game people say they cant here me and when i place the camera and i walk away from it i cant hear anything

### ISSUE THREAD

**Issue by XLIKES1** [wryser/Wrysers-GoPro#5] opened 2022-10-23 09:47 UTC

**Comment by wryser** [comment] 2023-01-07 01:39
ill have a look at this

**Comment by wryser** [comment] 2023-01-07 02:20
either the issue is somehow fixed with the new update or its something on your side since my mic works perfectly along with my audio

**Closed as completed by wryser** 2023-01-07 02:20 UTC
